[project]
name = "newton-sim"
version = "0.1.0"
description = "Newton robotics simulation tools"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "h5py>=3.16.0",
    "matplotlib>=3.10.8",
    "meshio>=5.3.5",
    "newton[examples]",
    "pandas>=2.3.3",
    "scipy>=1.15.3",
]

[tool.uv.sources]
newton = { path = "../../newton", editable = true }

[[tool.uv.index]]
url = "https://pypi.org/simple"

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com/"
explicit = true

[[tool.uv.index]]
name = "mujoco"
url = "https://py.mujoco.org"
explicit = true

# Override sources from newton's pyproject.toml
[tool.uv.sources.warp-lang]
index = "nvidia"

[tool.uv.sources.mujoco]
index = "mujoco"

[tool.uv.sources.mujoco-warp]
git = "https://github.com/google-deepmind/mujoco_warp"
