tetMesh: tacIL_gripper_v2.msh
selections: [
   "../selectors/selector_A1.obj",
   "../selectors/selector_A2.obj",
   "../selectors/selector_B1.obj",
   "../selectors/selector_B2.obj",
   "../selectors/selector_C1.obj",
   "../selectors/selector_C2.obj",
   "../selectors/selector_dirichlet.obj",
]