tetMesh: ThighpadRemake - Part.msh
selections: [
  "../selectors/ThighpadRemake - selectorBase.obj",
  "../selectors/ThighpadRemake - selectorInterior.obj",
  "../selectors/ThighpadRemake - selectorTop.obj",
]
