tetMesh: pad.msh
selections: [
  "../selectors/SelectorDirichlet.obj",
  "../selectors/SelectorX1.obj",
  "../selectors/SelectorX2.obj",
  "../selectors/SelectorX3.obj",
  "../selectors/SelectorY1.obj",
  "../selectors/SelectorY2.obj",
  "../selectors/SelectorY3.obj",
]
